# Generated by Django 4.0.3 on 2022-03-04 23:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True, verbose_name='Идентификатор справочника')),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование справочника')),
                ('short_name', models.CharField(max_length=128, verbose_name='Краткое наименование справочника')),
                ('description', models.TextField(verbose_name='Описание справочника')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, verbose_name='Версия справочника')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.resource', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версии справочника',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Код элемента')),
                ('value', models.CharField(max_length=256, verbose_name='Значение элемента')),
                ('resource_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.resourceversion', verbose_name='Версия справочника')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='resourceversion',
            constraint=models.UniqueConstraint(fields=('resource', 'version'), name='unique_version_for_resource'),
        ),
    ]
