# Generated by Django 4.0.3 on 2022-03-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['identifier', '-valid_from'], 'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
    ]
